language: rust
rust:
  - stable
  - beta

matrix:
  include:
    - os: linux
      name: 'Linux'
      dist: bionic
    - os: windows
      name: 'Windows'
    - os: osx
      name: 'OSX'

script:
  - cargo build
  - cargo test
  
notifications:
  email: false