language: rust

matrix:
  include:
    - os: linux
      name: 'Linux'
      dist: bionic
      rust:
        - stable
        - beta
    - os: windows
      name: 'Windows'
      rust:
        - stable
        - beta
    - os: osx
      name: 'OSX'
      rust:
        - stable
        - beta

script:
  - cargo build
  - cargo test
  
notifications:
  email: false